// ignore_for_file: unnecessary_null_comparison, import_of_legacy_library_into_null_safe

import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
import 'package:pokedex/consts/consts_app.dart';
import 'package:pokedex/models/pokeapi.dart';
import 'package:pokedex/pages/home_page/widgets/app_bar_home.dart';
import 'package:pokedex/pages/home_page/widgets/poke_item.dart';
import 'package:pokedex/stores/pokeapi_store.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  PokeApiStore? pokeApiStore;

  @override
  void initState() {
    super.initState();
    Autogenerated().pokemon;
    pokeApiStore = PokeApiStore();
    pokeApiStore?.fetchPokemonList();
  }

  @override
  Widget build(BuildContext context) {
    double screenWidth = MediaQuery.of(context).size.width;
    double statusWidth = MediaQuery.of(context).padding.top;

    return Scaffold(
      backgroundColor: Colors.white,
      body: Stack(
        alignment: Alignment.center,
        children: <Widget>[
          Positioned(
            top: -(450 / 3),
            left: screenWidth - (450 / 1.3),
            child: Opacity(
              opacity: 0.1,
              child: Image.asset(
                ConstApp.blackPokeball,
                height: 550,
                width: 550,
              ),
            ),
          ),
          Column(
            children: <Widget>[
              Container(
                height: statusWidth,
              ),
              const AppBarHome(),
              Expanded(
                child: Observer(
                    name: "ListaHomePage",
                    builder: (BuildContext context) {
                      Autogenerated? _autogenerated =
                          pokeApiStore?.autogenerated;
                      return (_autogenerated != null)
                          ? AnimationLimiter(
                              child: GridView.builder(
                                physics: const BouncingScrollPhysics(),
                                padding: const EdgeInsets.all(12),
                                addAutomaticKeepAlives: true,
                                gridDelegate:
                                    const SliverGridDelegateWithFixedCrossAxisCount(
                                        crossAxisCount: 2),
                                itemCount:
                                    pokeApiStore!.autogenerated.pokemon?.length,
                                itemBuilder: (context, index) {
                                  Pokemon pokemon =
                                      pokeApiStore?.getPokemon(index: index);
                                  return AnimationConfiguration.staggeredGrid(
                                    position: index,
                                    duration: const Duration(milliseconds: 375),
                                    columnCount: 2,
                                    child: ScaleAnimation(
                                      child: GestureDetector(
                                        child: PokeItem(
                                          types: pokemon.type,
                                          index: index,
                                          name: pokemon.name,
                                          num: pokemon.num,
                                        ),
                                        onTap: () {
                                          Navigator.push(
                                              context,
                                              MaterialPageRoute(
                                                builder: (BuildContext
                                                        context) =>
                                                    Container() /*PokeDetailPage(index: index)*/,
                                                fullscreenDialog: true,
                                              ));
                                        },
                                      ),
                                    ),
                                  );
                                },
                              ),
                            )
                          : const Center(
                              child: CircularProgressIndicator(),
                            );
                    }),
              ),
            ],
          )
        ],
      ),
    );
  }
}
