// ignore_for_file: import_of_legacy_library_into_null_safe, unused_local_variable

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:pokedex/consts/consts_api.dart';
import 'package:pokedex/models/pokeapi.dart';
import 'package:pokedex/stores/pokeapi_store.dart';
import 'package:provider/provider.dart';
import 'package:sliding_sheet/sliding_sheet.dart';

class PokeDatailPage extends StatefulWidget {
  final int index;
  final String name;

  const PokeDatailPage({Key? key, required this.index, required this.name})
      : super(key: key);

  @override
  State<PokeDatailPage> createState() => _PokeDatailPageState();
}

class _PokeDatailPageState extends State<PokeDatailPage> {
  Color? _corPokemon;

  @override
  Widget build(BuildContext context) {
    final _pokemonStore = Provider.of<PokeApiStore>(context);
    Pokemon? _pokemon = _pokemonStore.pokemonAtual;
    _corPokemon = ConstsAPI.getColorType(type: _pokemon!.type![0]);
    return Observer(
      builder: (BuildContext context) {
        return Scaffold(
          appBar: PreferredSize(
            preferredSize: const Size.fromHeight(50),
            child: Observer(builder: (context) {
              _corPokemon = ConstsAPI.getColorType(
                  type: _pokemonStore.pokemonAtual!.type![0]);
              return AppBar(
                title: Opacity(
                  opacity: 0.0,
                  child: Text(
                    _pokemon.name ?? '',
                    style: const TextStyle(
                      fontFamily: 'Google',
                      fontWeight: FontWeight.bold,
                      fontSize: 21,
                    ),
                  ),
                ),
                elevation: 0,
                backgroundColor: _corPokemon,
                leading: IconButton(
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () {
                    Navigator.pop(context);
                  },
                ),
                actions: <Widget>[
                  IconButton(
                    icon: const Icon(Icons.favorite_border),
                    onPressed: () {},
                  ),
                ],
              );
            }),
          ),
          body: Stack(
            children: <Widget>[
              Observer(builder: (context) {
                _corPokemon = ConstsAPI.getColorType(
                    type: _pokemonStore.pokemonAtual!.type![0]);
                return Container(color: _corPokemon);
              }),
              Container(height: MediaQuery.of(context).size.height / 3),
              SlidingSheet(
                elevation: 0,
                cornerRadius: 16,
                snapSpec: const SnapSpec(
                  snap: true,
                  snappings: [0.7, 1.0],
                  positioning: SnapPositioning.relativeToAvailableSpace,
                ),
                builder: (context, state) {
                  return Container(
                    height: MediaQuery.of(context).size.height,
                  );
                },
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 85),
                child: SizedBox(
                  height: 200,
                  child: PageView.builder(
                    onPageChanged: (index) {
                      _pokemonStore.setPokemonAtual(index: index);
                    },
                    itemCount: _pokemonStore.autogenerated!.pokemon?.length,
                    itemBuilder: (BuildContext context, int count) {
                      Pokemon _pokeItem =
                          _pokemonStore.getPokemon(index: count);
                      return CachedNetworkImage(
                        height: 60,
                        width: 60,
                        placeholder: (context, url) => Container(
                          color: Colors.transparent,
                        ),
                        imageUrl:
                            'https://raw.githubusercontent.com/fanzeyi/pokemon.json/master/images/${_pokeItem.num}.png',
                      );
                    },
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
