import 'dart:convert';

import 'package:mobx/mobx.dart';
import 'package:pokedex/consts/consts_api.dart';
import 'package:pokedex/models/pokeapi.dart';
import 'package:http/http.dart' as http;
part 'pokeapi_store.g.dart';

class PokeApiStore = _PokeApiStoreBase with _$PokeApiStore;

abstract class _PokeApiStoreBase with Store {

@observable
  late Autogenerated autogenerated;

@action
  fetchPokemonList() {
    loadAutogenerated().then((pokeList){
      autogenerated = pokeList!;
    });
}

  Future<Autogenerated?> loadAutogenerated() async {
    try{
      final response = await http.get(ConstsAPI.pokeapiURl);
      var decodeJson = jsonDecode(response.body);
      return Autogenerated.fromJson(decodeJson);
    }catch (error) {
      print("Error ao carregar lista");
      return null;
      }
    }
  }

